import { access, constants, mkdir, readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Fill, HoleKind } from './types';

/**
 * An unfilled hole answers with this. No NUL (it could not survive argv), no
 * `/` (it would corrupt any path built from it), control characters so it
 * cannot collide with plausible script output, and delimited on both sides so
 * a truncating `cut` or `head -c` is detectable rather than silent.
 */
export const HOLE_SENTINEL_PATTERN = /\x01h([0-9.]+)\x01/;

/**
 * A fresh global matcher; the pattern is stateful when reused, so callers get
 * their own.
 *
 * Matches two spellings. Raw bytes are what the shim writes and what ends up in
 * filenames on disk. But bash renders a control character with ANSI-C quoting,
 * so `declare -p` and xtrace both report the value as the *text* $'\001h1.2\001'
 * — which means the raw bytes never appear in the trace at all.
 */
export const holeSentinelMatcher = (): RegExp =>
  /\x01h([0-9.]+)\x01|\\001h([0-9.]+)\\001/g;

/** 2026-01-01T00:00:00Z — any fixed instant will do, so long as two runs agree. */
export const DEFAULT_CLOCK_EPOCH = 1767225600;

const BINARY_SEARCH_PATH = [
  '/usr/bin', '/bin', '/usr/local/bin', '/opt/homebrew/bin', '/usr/sbin', '/sbin',
];

/**
 * Resolved here rather than looked up at run time, because the shim sits first
 * on PATH and would otherwise find itself.
 */
async function resolveRealBinary(name: string): Promise<string | null> {
  for (const directory of BINARY_SEARCH_PATH) {
    const candidate = join(directory, name);
    try {
      await access(candidate, constants.X_OK);
      return candidate;
    } catch {
      continue;
    }
  }
  return null;
}

/** Always quotes, unlike `quoteShellWord`, because these land inside generated bash. */
function singleQuote(value: string): string {
  return `'${value.split("'").join(`'\\''`)}'`;
}

/** One file in the shim directory: the logic shared by every command it names. */
interface ShimDefinition {
  file: string;
  names: string[];
  fills?: HoleKind;
  needsRealBinary: boolean;
  body: string;
}

const HEADER_LINE = /^#\s*([a-z-]+):(.*)$/;
/** `@file` fills are on disk before the run and `@clock` is the epoch, so no shim answers from them. */
const FILL_KINDS: readonly string[] = ['net', 'cmd'] satisfies HoleKind[];

/**
 * Reads the `# key: value` lines a shim file opens with. They end at the first
 * line that is not one, so ordinary comments can follow; a lowercase key up
 * there that is not known is taken for a typo rather than skipped, because a
 * mistyped `fills` would otherwise quietly leave the shim with none.
 */
function parseShimFile(file: string, text: string): ShimDefinition {
  const definition: ShimDefinition = { file, names: [], needsRealBinary: false, body: text };
  const refuse = (why: string) => new Error(`Shim file ${file}: ${why}`);

  for (const line of text.split('\n')) {
    const header = HEADER_LINE.exec(line);
    if (!header) break;
    const key = header[1]!;
    const value = header[2]!.trim();
    if (key === 'shims') {
      definition.names.push(...value.split(/\s+/).filter(Boolean));
    } else if (key === 'fills') {
      if (!FILL_KINDS.includes(value)) {
        throw refuse(`"fills: ${value}" is not one of ${FILL_KINDS.join(', ')}.`);
      }
      definition.fills = value as HoleKind;
    } else if (key === 'real-binary') {
      if (value !== 'required') throw refuse(`"real-binary: ${value}" can only be "required".`);
      definition.needsRealBinary = true;
    } else {
      throw refuse(`unknown header "${key}".`);
    }
  }

  if (definition.names.length === 0) throw refuse('it has no "# shims: <name> ..." line.');
  return definition;
}

/** Every `*.sh` is a shim file, except `_`-prefixed ones, which are shared. */
async function loadShimDefinitions(sourceDirectory: string): Promise<ShimDefinition[]> {
  const files = (await readdir(sourceDirectory))
    .filter((file) => file.endsWith('.sh') && !file.startsWith('_'))
    .sort();
  const definitions = await Promise.all(
    files.map(async (file) => parseShimFile(file, await readFile(join(sourceDirectory, file), 'utf8'))),
  );

  const claimedBy = new Map<string, string>();
  for (const { file, names } of definitions) {
    for (const name of names) {
      const earlier = claimedBy.get(name);
      if (earlier) throw new Error(`Shim ${name} is claimed by both ${earlier} and ${file}.`);
      claimedBy.set(name, file);
    }
  }
  return definitions;
}

/**
 * The only generated part of a shim: values, never logic. Everything is
 * single-quoted, so a fill body carries quotes, `$`, backticks and newlines
 * through intact.
 */
function renderValues(values: { name: string; real?: string; epoch: number; fills: Fill[] }): string {
  const array = (items: string[]) => `(${items.map(singleQuote).join(' ')})`;
  return [
    '#!/usr/bin/env bash',
    '# Generated by bashle for one probe run. Not part of your workspace.',
    `_bashle_name=${singleQuote(values.name)}`,
    ...(values.real ? [`_bashle_real=${singleQuote(values.real)}`] : []),
    `_bashle_epoch=${values.epoch}`,
    `_bashle_fill_requests=${array(values.fills.map((fill) => fill.request))}`,
    `_bashle_fill_bodies=${array(values.fills.map((fill) => fill.body))}`,
    `_bashle_fill_codes=${array(values.fills.map((fill) => String(fill.exitCode)))}`,
  ].join('\n');
}

function pinnedEpoch(fills: Fill[]): number {
  const clock = fills.find((fill) => fill.kind === 'clock');
  const epoch = clock ? Math.floor(Date.parse(clock.body) / 1000) : DEFAULT_CLOCK_EPOCH;
  return Number.isFinite(epoch) ? epoch : DEFAULT_CLOCK_EPOCH;
}

export interface GenerateShimsOptions {
  binDirectory: string;
  /** Where the shim files live: `resources/shims`, beside the prelude. */
  sourceDirectory: string;
  fills: Fill[];
}

/**
 * Written for every shimmed name on every run, filled or not, because
 * discovery has to work before any fill exists. Each one is the run's values,
 * then `_preamble.sh`, then the file that names it.
 */
export async function generateShims({
  binDirectory,
  sourceDirectory,
  fills,
}: GenerateShimsOptions): Promise<void> {
  const [definitions, preamble] = await Promise.all([
    loadShimDefinitions(sourceDirectory),
    readFile(join(sourceDirectory, '_preamble.sh'), 'utf8'),
    mkdir(binDirectory, { recursive: true }),
  ]);
  const epoch = pinnedEpoch(fills);

  const written = definitions.flatMap((definition) => {
    const ownFills = definition.fills ? fills.filter((fill) => fill.kind === definition.fills) : [];
    return definition.names.map(async (name) => {
      const real = definition.needsRealBinary ? await resolveRealBinary(name) : undefined;
      // Pass-through needs the real binary, so a name we cannot resolve is left
      // unshimmed rather than shimmed into something that cannot delegate.
      if (real === null) return;
      const values = renderValues({ name, ...(real ? { real } : {}), epoch, fills: ownFills });
      await writeFile(join(binDirectory, name), `${values}\n${preamble}\n${definition.body}`, {
        mode: 0o755,
      });
    });
  });

  await Promise.all(written);
}
