import { mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Fill, HoleKind } from './types';

/**
 * An unfilled hole answers with this. No NUL (it could not survive argv), no
 * `/` (it would corrupt any path built from it), control characters so it
 * cannot collide with plausible script output, and delimited on both sides so
 * a truncating `cut` or `head -c` is detectable rather than silent.
 */
export const HOLE_SENTINEL_PATTERN = /\x01h([0-9.]+)\x01/;

/** A fresh global matcher; the pattern is stateful when reused, so callers get their own. */
export const holeSentinelMatcher = (): RegExp => /\x01h([0-9.]+)\x01/g;

/** Commands whose argv carries a URL, so the request is `<METHOD> <url>`. */
export const NETWORK_COMMANDS = ['curl', 'wget'] as const;

/** Commands that do their work in another process, which a file sandbox cannot contain. */
export const ESCAPE_COMMANDS = [
  'nc',
  'docker',
  'systemctl',
  'launchctl',
  'ssh',
  'aws',
  'kubectl',
] as const;

/** Always quotes, unlike `quoteShellWord`, because these land inside generated bash. */
function singleQuote(value: string): string {
  return `'${value.split("'").join(`'\\''`)}'`;
}

const PREAMBLE = `#!/usr/bin/env bash
# Generated by bashle for one probe run. Not part of your workspace.
_bashle_token="$$.$RANDOM"

# Small enough to stay under PIPE_BUF (512 bytes on macOS), so it cannot
# interleave with the tracer's own writes to fd 9. The body never goes here.
_bashle_record() {
  local request=$2
  (( \${#request} > 400 )) && request="\${request:0:400}…"
  printf '\\036H\\037%s\\037%s\\037%s\\037%s\\037%s\\037' \\
    "$1" "$request" "$_bashle_token" "$3" "$4" >&9 2>/dev/null || :
}
`;

/**
 * Derives `<METHOD> <url>` from a curl/wget invocation. Only a known flag
 * subset is understood; anything else is skipped, and an invocation with no
 * recognisable URL still produces a request rather than failing.
 */
const NETWORK_REQUEST = `
_bashle_method=GET
_bashle_url=
_bashle_output=
while (( $# )); do
  case "$1" in
    -X|--request) _bashle_method="\${2-}"; shift; shift 2>/dev/null || : ;;
    -d|--data|--data-raw|--data-binary|--data-urlencode)
      _bashle_method=POST; shift; shift 2>/dev/null || : ;;
    -o|--output) _bashle_output="\${2-}"; shift; shift 2>/dev/null || : ;;
    http://*|https://*) _bashle_url="$1"; shift ;;
    *) shift ;;
  esac
done
_bashle_request="$_bashle_method $_bashle_url"
`;

const commandRequest = (name: string): string => `
if (( $# )); then _bashle_request=${singleQuote(name)}" $*"; else _bashle_request=${singleQuote(name)}; fi
`;

/**
 * One branch per fill. Compared with `[[ ]]` and a quoted right-hand side
 * rather than `case`, because a request containing `*`, `?` or `[` is a glob
 * to `case` and would match the wrong thing.
 */
function renderFillBranches(fills: Fill[], kind: HoleKind, writesOutput: boolean): string {
  return fills
    .map((fill) => {
      const emit = writesOutput
        ? `  if [[ -n $_bashle_output ]]; then printf '%s' ${singleQuote(fill.body)} > "$_bashle_output"\n` +
          `  else printf '%s' ${singleQuote(fill.body)}; fi`
        : `  printf '%s' ${singleQuote(fill.body)}`;
      return [
        `if [[ $_bashle_request == ${singleQuote(fill.request)} ]]; then`,
        `  _bashle_record ${singleQuote(kind)} "$_bashle_request" ${fill.exitCode} filled`,
        emit,
        `  exit ${fill.exitCode}`,
        `fi`,
      ].join('\n');
    })
    .join('\n');
}

const openHole = (kind: HoleKind): string => `
_bashle_record ${singleQuote(kind)} "$_bashle_request" 0 open
printf '\\001h%s\\001' "$_bashle_token"
exit 0
`;

export function renderShim(options: { name: string; kind: HoleKind; fills: Fill[] }): string {
  const isNetwork = (NETWORK_COMMANDS as readonly string[]).includes(options.name);
  return [
    PREAMBLE,
    isNetwork ? NETWORK_REQUEST : commandRequest(options.name),
    renderFillBranches(options.fills, options.kind, isNetwork),
    openHole(options.kind),
  ].join('\n');
}

export interface GenerateShimsOptions {
  binDirectory: string;
  fills: Fill[];
}

/**
 * Written for every shimmed name on every run, filled or not, because
 * discovery has to work before any fill exists.
 */
export async function generateShims({
  binDirectory,
  fills,
}: GenerateShimsOptions): Promise<void> {
  await mkdir(binDirectory, { recursive: true });

  const shims: { name: string; kind: HoleKind }[] = [
    ...NETWORK_COMMANDS.map((name) => ({ name, kind: 'net' as const })),
    ...ESCAPE_COMMANDS.map((name) => ({ name, kind: 'cmd' as const })),
  ];

  await Promise.all(
    shims.map(({ name, kind }) =>
      writeFile(
        join(binDirectory, name),
        renderShim({ name, kind, fills: fills.filter((fill) => fill.kind === kind) }),
        { mode: 0o755 },
      ),
    ),
  );
}
