import { access, constants, mkdir, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import type { Fill, HoleKind } from './types';

/**
 * An unfilled hole answers with this. No NUL (it could not survive argv), no
 * `/` (it would corrupt any path built from it), control characters so it
 * cannot collide with plausible script output, and delimited on both sides so
 * a truncating `cut` or `head -c` is detectable rather than silent.
 */
export const HOLE_SENTINEL_PATTERN = /\x01h([0-9.]+)\x01/;

/**
 * A fresh global matcher; the pattern is stateful when reused, so callers get
 * their own.
 *
 * Matches two spellings. Raw bytes are what the shim writes and what ends up in
 * filenames on disk. But bash renders a control character with ANSI-C quoting,
 * so `declare -p` and xtrace both report the value as the *text* $'\001h1.2\001'
 * — which means the raw bytes never appear in the trace at all.
 */
export const holeSentinelMatcher = (): RegExp =>
  /\x01h([0-9.]+)\x01|\\001h([0-9.]+)\\001/g;

/** Commands whose argv carries a URL, so the request is `<METHOD> <url>`. */
export const NETWORK_COMMANDS = ['curl', 'wget'] as const;

/** Commands that do their work in another process, which a file sandbox cannot contain. */
export const ESCAPE_COMMANDS = [
  'nc',
  'docker',
  'systemctl',
  'launchctl',
  'ssh',
  'aws',
  'kubectl',
] as const;

/**
 * Commands where *every* non-flag argument is a file, so the shim can test
 * existence without parsing a grammar. `grep`, `sed`, `awk` and `jq` are
 * deliberately absent: their first non-flag argument is a pattern, and a wrong
 * guess would invent a hole for a file nobody named.
 */
export const FILE_READER_COMMANDS = [
  'cat', 'head', 'tail', 'tac', 'nl', 'wc', 'sort', 'uniq', 'cut',
  'od', 'xxd', 'base64', 'cksum', 'shasum', 'md5sum', 'file',
  'stat', 'realpath', 'readlink', 'du',
] as const;

/** Answered from a fixed default so they do not drown the list of real unknowns. */
export const PREFILLED_COMMANDS: { name: string; value: string }[] = [
  { name: 'hostname', value: 'bashle' },
  { name: 'whoami', value: 'bashle' },
  { name: 'uuidgen', value: '00000000-0000-4000-8000-000000000000' },
];

/** 2026-01-01T00:00:00Z — any fixed instant will do, so long as two runs agree. */
export const DEFAULT_CLOCK_EPOCH = 1767225600;

const BINARY_SEARCH_PATH = [
  '/usr/bin', '/bin', '/usr/local/bin', '/opt/homebrew/bin', '/usr/sbin', '/sbin',
];

/**
 * Resolved here rather than looked up at run time, because the shim sits first
 * on PATH and would otherwise find itself.
 */
async function resolveRealBinary(name: string): Promise<string | null> {
  for (const directory of BINARY_SEARCH_PATH) {
    const candidate = join(directory, name);
    try {
      await access(candidate, constants.X_OK);
      return candidate;
    } catch {
      continue;
    }
  }
  return null;
}

/** Always quotes, unlike `quoteShellWord`, because these land inside generated bash. */
function singleQuote(value: string): string {
  return `'${value.split("'").join(`'\\''`)}'`;
}

const PREAMBLE = `#!/usr/bin/env bash
# Generated by bashle for one probe run. Not part of your workspace.
_bashle_token="$$.$RANDOM"

# Small enough to stay under PIPE_BUF (512 bytes on macOS), so it cannot
# interleave with the tracer's own writes to fd 9. The body never goes here.
_bashle_record() {
  local request=$2
  (( \${#request} > 400 )) && request="\${request:0:400}…"
  printf '\\036H\\037%s\\037%s\\037%s\\037%s\\037%s\\037' \\
    "$1" "$request" "$_bashle_token" "$3" "$4" >&9 2>/dev/null || :
}
`;

/**
 * Derives `<METHOD> <url>` from a curl/wget invocation. Only a known flag
 * subset is understood; anything else is skipped, and an invocation with no
 * recognisable URL still produces a request rather than failing.
 */
const NETWORK_REQUEST = `
_bashle_method=GET
_bashle_url=
_bashle_output=
while (( $# )); do
  case "$1" in
    -X|--request) _bashle_method="\${2-}"; shift; shift 2>/dev/null || : ;;
    -d|--data|--data-raw|--data-binary|--data-urlencode)
      _bashle_method=POST; shift; shift 2>/dev/null || : ;;
    -o|--output) _bashle_output="\${2-}"; shift; shift 2>/dev/null || : ;;
    http://*|https://*) _bashle_url="$1"; shift ;;
    *) shift ;;
  esac
done
_bashle_request="$_bashle_method $_bashle_url"
`;

const commandRequest = (name: string): string => `
if (( $# )); then _bashle_request=${singleQuote(name)}" $*"; else _bashle_request=${singleQuote(name)}; fi
`;

/**
 * One branch per fill. Compared with `[[ ]]` and a quoted right-hand side
 * rather than `case`, because a request containing `*`, `?` or `[` is a glob
 * to `case` and would match the wrong thing.
 */
function renderFillBranches(fills: Fill[], kind: HoleKind, writesOutput: boolean): string {
  return fills
    .map((fill) => {
      const emit = writesOutput
        ? `  if [[ -n $_bashle_output ]]; then printf '%s' ${singleQuote(fill.body)} > "$_bashle_output"\n` +
          `  else printf '%s' ${singleQuote(fill.body)}; fi`
        : `  printf '%s' ${singleQuote(fill.body)}`;
      return [
        `if [[ $_bashle_request == ${singleQuote(fill.request)} ]]; then`,
        `  _bashle_record ${singleQuote(kind)} "$_bashle_request" ${fill.exitCode} filled`,
        emit,
        `  exit ${fill.exitCode}`,
        `fi`,
      ].join('\n');
    })
    .join('\n');
}

const openHole = (kind: HoleKind): string => `
_bashle_record ${singleQuote(kind)} "$_bashle_request" 0 open
printf '\\001h%s\\001' "$_bashle_token"
exit 0
`;

/**
 * Passes through when every named file is there, and holes only on genuine
 * absence — a file that is in the clone stays real, which is the point of the
 * clone. A `@file` fill never reaches the hole branch, because materialization
 * put the file on disk before the run started.
 */
function renderFileReaderShim(name: string, realPath: string): string {
  return `${PREAMBLE}
_bashle_missing=
_bashle_skip_next=
for _bashle_arg in "$@"; do
  if [[ -n $_bashle_skip_next ]]; then _bashle_skip_next=; continue; fi
  case "$_bashle_arg" in
    -|--) continue ;;
    # A lone short flag is the shape that takes a separate value, so whatever
    # follows it is not a filename. Skipping it can miss a hole; not skipping
    # it would invent one for a value like the 2 in "head -n 2", and a false
    # hole is the worse failure by far.
    -[a-zA-Z]) _bashle_skip_next=1; continue ;;
    -*) continue ;;
  esac
  [[ -e $_bashle_arg ]] || { _bashle_missing=$_bashle_arg; break; }
done

if [[ -z $_bashle_missing ]]; then
  exec ${singleQuote(realPath)} "$@"
fi

_bashle_request=$_bashle_missing
_bashle_record 'file' "$_bashle_request" 0 open
printf '\\001h%s\\001' "$_bashle_token"
exit 0
`;
}

function renderClockShim(realPath: string, epoch: number, fills: Fill[]): string {
  return [
    PREAMBLE,
    commandRequest('date'),
    renderFillBranches(fills, 'cmd', false),
    `_bashle_record 'clock' "$_bashle_request" 0 prefilled`,
    `${singleQuote(realPath)} -d "@${epoch}" "$@" 2>/dev/null || ${singleQuote(realPath)} -r ${epoch} "$@"`,
  ].join('\n');
}

function renderPrefilledShim(name: string, value: string, fills: Fill[]): string {
  return [
    PREAMBLE,
    commandRequest(name),
    renderFillBranches(fills, 'cmd', false),
    `_bashle_record 'cmd' "$_bashle_request" 0 prefilled`,
    `printf '%s\\n' ${singleQuote(value)}`,
    `exit 0`,
  ].join('\n');
}

export function renderShim(options: { name: string; kind: HoleKind; fills: Fill[] }): string {
  const isNetwork = (NETWORK_COMMANDS as readonly string[]).includes(options.name);
  return [
    PREAMBLE,
    isNetwork ? NETWORK_REQUEST : commandRequest(options.name),
    renderFillBranches(options.fills, options.kind, isNetwork),
    openHole(options.kind),
  ].join('\n');
}

export interface GenerateShimsOptions {
  binDirectory: string;
  fills: Fill[];
}

/**
 * Written for every shimmed name on every run, filled or not, because
 * discovery has to work before any fill exists.
 */
export async function generateShims({
  binDirectory,
  fills,
}: GenerateShimsOptions): Promise<void> {
  await mkdir(binDirectory, { recursive: true });

  const cmdFills = fills.filter((fill) => fill.kind === 'cmd');
  const written: Promise<unknown>[] = [];
  const write = (name: string, contents: string): void => {
    written.push(writeFile(join(binDirectory, name), contents, { mode: 0o755 }));
  };

  for (const name of NETWORK_COMMANDS) {
    write(name, renderShim({ name, kind: 'net', fills: fills.filter((f) => f.kind === 'net') }));
  }
  for (const name of ESCAPE_COMMANDS) {
    write(name, renderShim({ name, kind: 'cmd', fills: cmdFills }));
  }

  // Pass-through needs the real binary, so a name we cannot resolve is left
  // unshimmed rather than shimmed into something that cannot delegate.
  for (const name of FILE_READER_COMMANDS) {
    const realPath = await resolveRealBinary(name);
    if (realPath) write(name, renderFileReaderShim(name, realPath));
  }
  for (const { name, value } of PREFILLED_COMMANDS) {
    write(name, renderPrefilledShim(name, value, cmdFills));
  }

  const clock = fills.find((fill) => fill.kind === 'clock');
  const epoch = clock ? Math.floor(Date.parse(clock.body) / 1000) : DEFAULT_CLOCK_EPOCH;
  const realDate = await resolveRealBinary('date');
  if (realDate) {
    write('date', renderClockShim(realDate, Number.isFinite(epoch) ? epoch : DEFAULT_CLOCK_EPOCH, cmdFills));
  }

  await Promise.all(written);
}
